import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { MemberRole } from "@prisma/client";
import { getClientStatement } from "@/server/db/client-statements";
import { getClientForUI, isLiveDb } from "@/server/data/source";
import { resolveTenantContext } from "@/server/data/tenant";

/**
 * Phase 2.13.4 — Statement detail.
 *
 * Read-only view of a single persisted snapshot. The CSV export button
 * routes to `/api/clients/[id]/statements/[statementId]` (auth-gated).
 *
 * PDF export + "Send to client portal" CTA are deferred (PDF needs the
 * heavy `@react-pdf/renderer` dep; portal-send waits for 2.13.8). Once
 * those land they slot in next to the CSV button.
 */

function formatShortDate(d: Date): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(d);
}

function formatCurrencyUsd(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
  }).format(cents / 100);
}

export default async function ClientStatementDetailPage({
  params,
}: {
  params: Promise<{ key: string; id: string }>;
}) {
  const { key, id } = await params;
  const tenant = await resolveTenantContext();
  if (tenant.role !== MemberRole.OWNER && tenant.role !== MemberRole.ADMIN) {
    redirect(`/clients/${key}`);
  }

  const client = await getClientForUI(tenant, key);
  if (!client) notFound();

  // Sample-data mode: render an "unavailable" placeholder so the route
  // doesn't 500 on a synthetic id.
  if (!isLiveDb()) {
    return (
      <SampleDataNotice
        clientName={client.name}
        statementsHref={`/clients/${client.key}/statements`}
      />
    );
  }

  let statement;
  try {
    statement = await getClientStatement(tenant, id);
  } catch {
    notFound();
  }

  // Defence in depth — the repo already tenant-filters, but make sure the
  // URL key matches the statement's client (a manual URL with mismatched
  // keys shouldn't render a real statement).
  if (statement.client.id !== client.key) notFound();

  const generatedBy = statement.generatedByMember
    ? statement.generatedByMember.name?.trim() || statement.generatedByMember.email
    : "system";

  return (
    <div className="flex flex-col gap-5">
      <section className="border-border bg-surface flex flex-wrap items-start justify-between gap-4 rounded-3xl border p-5">
        <div>
          <Link
            href={`/clients/${client.key}/statements`}
            className="text-muted hover:text-ink mb-3 inline-flex items-center gap-[6px] font-sans text-[12.5px] font-medium transition-colors"
          >
            <svg
              width="13"
              height="13"
              viewBox="0 0 13 13"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.6"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M8 3L4 6.5l4 3.5" />
            </svg>
            All statements
          </Link>
          <div className="font-display text-ink text-[20px] font-semibold tracking-[-0.3px]">
            Statement — {formatShortDate(statement.periodStart)} →{" "}
            {formatShortDate(statement.periodEnd)}
          </div>
          <div className="text-muted-2 mt-1 text-[12.5px]">
            Generated by {generatedBy} on {formatShortDate(statement.generatedAt)}
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <a
            href={`/api/clients/${client.key}/statements/${statement.id}`}
            className="border-border text-accent hover:border-accent-border rounded-md border bg-white px-3 py-2 font-sans text-[12.5px] font-semibold transition-colors"
            download
          >
            Export CSV
          </a>
          <span
            className="border-border bg-canvas text-muted-2 cursor-not-allowed rounded-md border px-3 py-2 font-sans text-[12.5px] font-medium opacity-60"
            title="PDF export lands in a follow-up."
          >
            Export PDF
          </span>
          <span
            className="border-border bg-canvas text-muted-2 cursor-not-allowed rounded-md border px-3 py-2 font-sans text-[12.5px] font-medium opacity-60"
            title="Available once the client portal route (2.13.8) ships."
          >
            Send to client portal
          </span>
        </div>
      </section>

      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatBlock label="Episodes" value={statement.episodeCount} />
        <StatBlock label="Outputs" value={statement.outputCount} />
        <StatBlock
          label="Approved"
          value={`${statement.approvedCount} (${statement.approvalRatePct}%)`}
        />
        <StatBlock label="Cost to serve" value={formatCurrencyUsd(statement.costCents)} />
      </section>

      <section className="border-border bg-surface rounded-3xl border p-5">
        <div className="font-display text-ink text-[14px] font-semibold">About this statement</div>
        <div className="text-muted mt-2 text-[12.5px] leading-[1.55]">
          Totals are snapshotted at generation time and won&apos;t change if underlying outputs are
          later regenerated or edited. Use the CSV export to attach the period summary to your own
          invoice. Per-platform breakdown + PDF export ship in a follow-up; the &quot;Send to client
          portal&quot; button is enabled once the tokenized client portal (2.13.8) lands.
        </div>
      </section>
    </div>
  );
}

function StatBlock({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="border-border bg-surface rounded-2xl border p-4">
      <div className="text-muted-2 font-sans text-[11.5px] font-medium tracking-[0.05em] uppercase">
        {label}
      </div>
      <div className="font-display text-ink mt-2 text-[24px] font-bold tracking-[-0.4px]">
        {value}
      </div>
    </div>
  );
}

function SampleDataNotice({
  clientName,
  statementsHref,
}: {
  clientName: string;
  statementsHref: string;
}) {
  return (
    <section className="border-border bg-canvas rounded-3xl border border-dashed p-6 text-center">
      <div className="font-display text-ink text-[16px] font-semibold">Sample-data mode</div>
      <p className="text-muted mx-auto mt-2 max-w-[480px] text-[13px]">
        Statements are stored in the database — connect a Postgres URL and regenerate to see the
        persisted version for {clientName}.
      </p>
      <Link
        href={statementsHref}
        className="border-border text-muted hover:border-accent-border hover:text-accent mt-4 inline-flex rounded-md border bg-white px-3 py-2 font-sans text-[12.5px] font-medium"
      >
        Back to statements
      </Link>
    </section>
  );
}
