import { readFile, writeFile } from "node:fs/promises";
import { execa } from "execa";
import { srtStringToAss } from "./ass.js";

/**
 * Q1 feature #5 — audiogram (waveform video) ffmpeg pipeline.
 *
 * Composition:
 *   Layer 0: background — one of three modes:
 *     a) `bgImagePath` set → blurred + darkened artwork
 *     b) `bgImagePath` null → deep navy → violet diagonal gradient
 *        (generated inline via `blend`, no external assets required)
 *   Layer 1: `showwaves` in mint (`#7FE3B0`) — the brand accent — at 88 %
 *        height, ~7 % of the frame. Reads as a design element, not a
 *        debug overlay.
 *   Layer 2: subtitles burned in from srtPath (centered, large, white
 *        with black outline).
 *
 * All commands hard-timeout at 5 min to bound cost per render.
 */

/**
 * Gradient palette used when no background image is supplied. Deep navy
 * top-left → deep violet bottom-right. Chosen to complement the mint
 * waveform accent (`WAVE_COLOR`) — cool desaturated backdrop makes the
 * green pop without competing.
 */
const GRADIENT_TOP = "0x0A1E3C"; // deep navy
const GRADIENT_BOTTOM = "0x2E1A4A"; // deep violet
const WAVE_COLOR = "0x7FE3B0"; // mint — matches --color-accent in the UI

export type AudiogramAspect = "1:1" | "9:16";

const OUTPUT_DIMS: Record<AudiogramAspect, { w: number; h: number }> = {
  "1:1": { w: 1080, h: 1080 },
  "9:16": { w: 1080, h: 1920 },
};

/**
 * Render an audiogram MP4 from a trimmed audio window + optional
 * background image + burned-in captions.
 *
 * If `bgImagePath` is null, we render on a solid #0F1B2C background.
 * If it's set, we blur + darken the image and overlay the waveform.
 */
export async function renderAudiogramVideo(input: {
  audioPath: string;
  srtPath: string;
  bgImagePath: string | null;
  outputPath: string;
  startSec: number;
  endSec: number;
  aspect: AudiogramAspect;
}): Promise<void> {
  const { audioPath, srtPath, bgImagePath, outputPath, startSec, endSec, aspect } = input;
  const { w, h } = OUTPUT_DIMS[aspect];
  const durationSec = Math.max(1, endSec - startSec);

  // Waveform is a thin decorative band at the very bottom now — the
  // caption is the visual centrepiece, sitting dead-centre both
  // vertically and horizontally. Wave takes ~7 % of the frame,
  // anchored ~88 % down, so it reads as a footer rather than
  // competing with the text.
  const waveH = Math.round(h * 0.07);
  const waveY = Math.round(h * 0.88);

  // Convert the SRT to a proper ASS file with our styling baked into
  // the [V4+ Styles] block. See worker/src/lib/ass.ts for why we don't
  // trust ffmpeg's force_style anymore.
  const srtText = await readFile(srtPath, "utf8");
  const assPath = `${srtPath}.ass`;
  const assDocument = srtStringToAss(srtText, {
    fontName: "DejaVu Sans",
    fontSize: 88,
    primaryColor: "&H00FFFFFF",
    outlineColor: "&H00000000",
    backColor: "&H80000000",
    borderStyle: 3,
    outline: 12,
    shadow: 0,
    alignment: 5, // middle-center
    marginL: 100,
    marginR: 100,
    marginV: 0,
    bold: true,
    wrapStyle: 0,
    playResX: w,
    playResY: h,
  });
  await writeFile(assPath, assDocument, "utf8");
  const assEscaped = assPath.replace(/'/g, "\\'").replace(/:/g, "\\:");

  // Filter graph. The audio input gets its own trim so the whole file
  // isn't re-encoded; the waveform is generated from the trimmed audio.
  //
  // Gradient fallback uses two `color` sources blended along a diagonal:
  // `A*(1-(X+Y)/(W+H)) + B*((X+Y)/(W+H))` interpolates from top-left
  // (100 % top color) to bottom-right (100 % bottom color). The blend
  // runs on constant inputs so ffmpeg amortizes the per-pixel cost
  // across the render.
  const bgFilter = bgImagePath
    ? // Blurred + darkened artwork
      `[0:v]scale=${w}:${h}:force_original_aspect_ratio=increase,` +
      `crop=${w}:${h},boxblur=20:2,eq=brightness=-0.25[bg]`
    : // Diagonal navy → violet gradient
      `color=c=${GRADIENT_TOP}:s=${w}x${h}:d=${durationSec.toFixed(3)}[bgtop];` +
      `color=c=${GRADIENT_BOTTOM}:s=${w}x${h}:d=${durationSec.toFixed(3)}[bgbot];` +
      `[bgtop][bgbot]blend=all_expr='A*(1-(X+Y)/(W+H))+B*((X+Y)/(W+H))'[bg]`;

  const filter =
    `${bgFilter};` +
    `[1:a]atrim=${startSec.toFixed(3)}:${endSec.toFixed(3)},asetpts=PTS-STARTPTS[trimaudio];` +
    `[trimaudio]asplit=2[audio][audioWave];` +
    `[audioWave]showwaves=s=${w}x${waveH}:mode=cline:colors=${WAVE_COLOR}@0.9:rate=25[wave];` +
    `[bg][wave]overlay=0:${waveY}:shortest=1[bgwave];` +
    `[bgwave]subtitles='${assEscaped}'[vout]`;

  // Input layout depends on whether we have a background image. When we
  // do, input 0 is the still image (looped) and input 1 is the audio —
  // matching the `[0:v]` / `[1:a]` refs in the filter graph. When we
  // don't, the gradient is generated by two `color` sources inside the
  // graph and there's only one real input (the audio), so we rewrite
  // the audio ref from `[1:a]` to `[0:a]`.
  const finalInputs = bgImagePath
    ? ["-loop", "1", "-i", bgImagePath, "-i", audioPath]
    : ["-i", audioPath];
  const finalFilter = bgImagePath ? filter : filter.replace("[1:a]", "[0:a]");

  await execa(
    "ffmpeg",
    [
      "-y",
      "-nostdin",
      "-hide_banner",
      "-loglevel",
      "error",
      ...finalInputs,
      "-filter_complex",
      finalFilter,
      "-map",
      "[vout]",
      "-map",
      "[audio]",
      "-c:v",
      "libx264",
      "-preset",
      "veryfast",
      "-crf",
      "23",
      "-c:a",
      "aac",
      "-b:a",
      "128k",
      "-t",
      durationSec.toFixed(3),
      "-movflags",
      "+faststart",
      "-pix_fmt",
      "yuv420p",
      outputPath,
    ],
    { timeout: 5 * 60_000 },
  );
}
